### ISSUE TITLE
Naming ?

### ISSUE THREAD

**Issue by odnar-dev** [MyOS-ArchLinux/vids#16]
the rewrite is almost done 🙏🏻

~~i am thinking of changing the `LICENSE` to [GNU GPLv3](https://choosealicense.com/licenses/gpl-3.0/)~~

and i am also thinking of changing the name to `sspr` which stand for `search select play repeat (🔍 🔘 ⏯️ 🔁)`

**Comment by odnar-dev** [comment]
google search show more than 496,000 results for `sspr`
![image](https://user-images.githubusercontent.com/73726132/130698306-32a1da37-3260-4018-8382-752bfb5a4971.png)

look like SSPR stand for Self-Service Password Reset which is an Azure AD feature that enables users to reset their passwords without contacting IT staff for help...

but if i search for `vids` is show about 15,540,000 results
________
i like `vids` cause it sample and stand for `videos search` and also short for [videos](https://www.urbandictionary.com/define.php?term=vids)
but i also like `sspr` cause it's unique ([not really](https://www.google.com/search?q=sspr)),
and also stand for what you actually do when you use this script ; `search select play repeat`

**Comment by trueauracoral** [comment]
Maybe vid mix? 
Or vidix.
Or vidium.
I like vidmix. 

Welp those are taken.

OR even vidy. I search on brave search and I don't see anything with "vidy"

I like vidy quite a bit.

OR EVEN combine all the video platforms

Y - for youtube
I - for invidious ( Future thing, I will send a issue for it after I make this comment )
P - for peertube/piped
O - for odysee
B - for bitchute
T - for TED

Y I P O B T

Yipobt? Yibopt? Yitobp?

I really like Yibopt LOL

Well here are a bunch of names. Yibopt is my favorite. Also no search results that point to yibopt.
